mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      column-underline: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
#shardingjdbc配置
sharding:
  jdbc:
    data-sources:
      ###配置第一个从数据库
      ds_slave_0:
        password: Aa123456
        jdbc-url: jdbc:mysql://192.168.1.133:3306/world?useUnicode=true&characterEncoding=utf-8&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
      ds_slave_1:
        password: Aa123456
        jdbc-url: jdbc:mysql://192.168.1.134:3306/world?useUnicode=true&characterEncoding=utf-8&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
      ###主数据库配置
      ds_master:
        password: Aa123456
        jdbc-url: jdbc:mysql://192.168.1.132:3306/world?useUnicode=true&characterEncoding=utf-8&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
    ###配置读写分离
    master-slave-rule:
      ###配置从库选择策略，提供轮询与随机，这里选择用轮询
      load-balance-algorithm-type: round_robin
      ####指定从数据库
      slave-data-source-names: ds_slave_0,ds_slave_1
      name: ds_ms
      ####指定主数据库
      master-data-source-name: ds_master
    config:
      sharding:
        props:
          sql.show: true   #仅仅开启读写分离时,不打印sql
